version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY

  web:
    image: node
    command: bash /scripts/deploy/web_deploy.sh
    volumes:
    - ./frontend:/frontend
    - ./scripts:/scripts
    working_dir: /frontend
    depends_on:
      - api
    stdin_open: true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
      - ./backend/downtownapi/static:/var/www/backend
    depends_on:
      - web

volumes:
  db-data:
