version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/src:/frontend/src
    stdin_open: true

  nginx:
    image: nginx:latest
    ports:
      - 80:3000
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - api
volumes:
  db-data:
