version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn start
    volumes:
    - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    stdin_open: true

volumes:
  db-data:
