version: '3'
services: 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python /backend/downtownapi/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/src:/frontend/src
    stdin_open: true
