version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
    working_dir: /backend/downtownapi/
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY
      - PRODUCTION=True
      - STRIPE_KEY=$STRIPE_KEY
      - STRIPE_WEBHOOK_KEY=$STRIPE_WEBHOOK_KEY
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - CURRENT_ROUND=1
      - FIREBASE_KEY=$FIREBASE_KEY
      - FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      - FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
      - FIREBASE_APPID=$FIREBASE_APPID
      - FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always


#  web:
#    image: node
#    command: bash /scripts/deploy/web_deploy.sh
#    volumes:
#    - ./frontend:/frontend
#    - ./scripts:/scripts
#    working_dir: /frontend
#    depends_on:
#      - api
#    stdin_open: true
#    restart: always

  nginx:
    image: ethifylabs/downtownstimulus
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./frontend/build:/var/www/frontend
      - ./backend/downtownapi/static:/var/www/backend
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/downtownstimulus.com/fullchain.pem:/etc/letsencrypt/live/downtownstimulus.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/downtownstimulus.com/privkey.pem:/etc/letsencrypt/live/downtownstimulus.com/privkey.pem
    depends_on:
      - api
    environment:
      - REACT_APP_FIREBASE_KEY=$FIREBASE_KEY
      - REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      - REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
      - REACT_APP_FIREBASE_APPID=$FIREBASE_APPID
      - REACT_APP_FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - REACT_APP_STRIPE_KEY=$STRIPE_KEY
    restart: always

volumes:
  db-data:
